# Generated by Django 4.2.17 on 2024-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0003_temporderitem_pre_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporderitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='temporderitem',
            name='seat_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temporderitem',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
