# Generated by Django 4.2.17 on 2024-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0006_remove_orderitem_date_remove_orderitem_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
