# Generated by Django 4.2.17 on 2024-12-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0009_rename_time_temporder_time_start_temporder_time_end'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempOrderItem',
            new_name='CartItem',
        ),
    ]
