# Generated by Django 4.2.17 on 2024-12-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0010_rename_temporderitem_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='pre_order_discount',
            new_name='discount_rate',
        ),
    ]
