# Generated by Django 4.2.17 on 2024-12-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0012_rename_seat_id_reservation_seat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='reservation_number',
        ),
    ]
