# Generated by Django 4.2.17 on 2024-12-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0013_rename_reservation_id_reservation_reservation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='time_start',
        ),
    ]
