# Generated by Django 4.2.17 on 2024-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0015_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_with_tax',
            field=models.IntegerField(default=0),
        ),
    ]
