# Generated by Django 4.2.17 on 2024-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0019_orderitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
