# Generated by Django 4.2.17 on 2024-12-22 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0020_reservation_item_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deicafe_app.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='temp_order',
        ),
        migrations.DeleteModel(
            name='TempOrder',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reservation_draft',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deicafe_app.reservationdraft'),
        ),
    ]
