# Generated by Django 4.2.17 on 2024-12-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0024_remove_cartitem_reservation_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdraft',
            name='cart_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deicafe_app.cartitem'),
        ),
    ]
