# Generated by Django 4.2.17 on 2025-01-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0026_remove_reservationdraft_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_confirm',
            field=models.CharField(default='', max_length=20),
        ),
    ]
