# Generated by Django 4.2.17 on 2025-01-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0029_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Large size price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Medium size price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_s',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Small size price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
