# Generated by Django 4.2.17 on 2025-01-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0030_product_price_l_product_price_m_product_price_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
