# Generated by Django 4.2.17 on 2025-01-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0031_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
