# Generated by Django 4.2.17 on 2025-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafe_app', '0034_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='reservation',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
